# for developer testing
version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: calvin
      POSTGRES_PASSWORD: handsome
      POSTGRES_DB: bauhaus